### PR TITLE
Allow using other CMake generators besides "Unix Makefiles".

### PR DESCRIPTION
**Pull request by junhaoliao**
# Description

Previously, it was mandated in CMakeList.txt that only `Unix Makefiles` generators can be used because compilation errors were observed with code that references C++-20 headers. It is confirmed that now with Ninja generators, the `clp-ffi-js` code compiles fine with Emsdk @ 3.1.67 .

1. Remove "Unix Makefiles" `CMAKE_GENERATOR` check.
2. Eliminate the generator specification from compilation commands in Taskfile.

# Validation performed

1. On a Mac computer.
    1. Ran `task clp-ffi-js` and observed compilation success.
    2. Added a semantically meaningless newline at the end of StreamReader.cpp and ran `task clp-ffi-js` again. Observed the source code getting compiled and the overall compilation succeeded.
2. On an Ubuntu 20.04 computer, repeat above validation steps. (In my case, I was using WSL. )

## Summary by CodeRabbit

- **New Features**
	- Simplified build configuration by allowing various generators without restrictions.
	- Introduced new variables in task definitions for improved build clarity and reliability.
- **Bug Fixes**
	- Enhanced handling of the Boost library version for better compatibility.
- **Chores**
	- Updated task commands to ensure a clean build environment and consistent checksum validation.

### CODE REVIEW

**Comment by junhaoliao** [comment]
This PR shall merge with main once #18 is merged into main.

**Review by kirkrodrigues — APPROVED** [review]
For the PR title, how about:

Allow using other CMake generators besides "Unix Makefiles".
